# Generated by Django 6.0.6 on 2026-06-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exampleapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnmanagedThing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthorProxy",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("exampleapp.author",),
        ),
    ]
